### ISSUE TITLE
Doc: Search functionality does not work

### ISSUE THREAD

**Issue by jjimenezshaw** [jazzband/geojson#224] opened 2023-10-27 09:05 UTC
In the documentation in readthedocs, the Search functionality does not return anything. It stays "Searching..." forever.

https://python-geojson.readthedocs.io/en/latest/search.html?q=point&check_keywords=yes&area=default

**Comment by jjimenezshaw** [comment] 2023-10-27 09:06
@mwtoews that happened also during the migration to readthedocs in PROJ. Do you remember what happened

**Comment by mwtoews** [comment] 2023-10-27 09:19
The fix was from https://github.com/OSGeo/PROJ/commit/fd1b61e71c23fe959799fe6a5320fcf5d99a7a93

But I don't even see how this can be done for this repo. Also, the docs for this repo is only one page, so if anything the search should be disabled.

**Comment by jjimenezshaw** [comment] 2023-10-27 09:27
Thanks!

Search is the most noticeable thing, but there are other controls that do not work, like the version selector in the bottom left part "v: latest", or the whole menu button (burger button) when using it in a mobile device.

**Comment by mwtoews** [comment] 2023-10-27 09:29
Yeah, I noticed the non-working controls too, which was the same as from the broken PROJ docs too. It's probably missing sphinxcontrib.jquery from the extensions list.

**Comment by rayrrr** [comment] 2023-11-22 21:25
@mwtoews et al., thanks for reporting this issue and providing some tips. I'm looking into it now.

**Comment by blaisep** [comment] 2024-05-28 13:33
https://github.com/jazzband/help/issues/349#issuecomment-2135230760
@mwtoews , @jjimenezshaw

**Comment by rayrrr** [comment] 2024-08-07 01:42
The above-mentioned PR, #227, is an attempt to fix this issue based on the above discussion. @blaisep and/or @mwtoews would you be kind enough to give it a review? 

Basically, I used `sphinx-quickstart` to get a foundation, and then make some tweaks based on your recommendations.

**Comment by rayrrr** [comment] 2024-08-10 13:15
@blaisep et al., I went ahead and merged the fix for this without review since it didn't touch any package functionality, and the issue is now resolved. Thanks for reporting it @jjimenezshaw.

**Closed by rayrrr** 2024-08-10 13:15 UTC
